name: dart_lang_tr
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-245.0.dev <4.0.0"

dependencies:
  animate_do: ^3.0.2
  app_settings: ^4.2.0
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.2.0
  image_picker: ^0.8.6+3
  local_hero: ^0.2.0
  lottie: ^2.2.0
  permission_handler: ^10.2.0
  profanity_filter: ^2.0.0
  responsive_builder: ^0.6.0
  video_player: ^2.5.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/dart_images/
    - assets/videos/dart_videos/

flutter_assets:
  assets_path: assets/images/dart_images/
  output_path: lib/features/dart/constants/
  filename: image_assets.dart
