name: dart_lang_tr
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-245.0.dev <4.0.0"

dependencies:
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  local_hero: ^0.2.0
  video_player: ^2.5.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/dart_images/
    - assets/videos/dart_videos/

flutter_assets:
  assets_path: assets/images/dart_images/
  output_path: lib/features/dart/constants/
  filename: image_assets.dart
